### ISSUE TITLE
`opam install sibylfs` fails

### ISSUE THREAD

**Issue by HenkPoley** [sibylfs/sibylfs_src#14]
How to get it installed, on Ubuntu 14.04:

<pre><code>opam install sibylfs sha.1.8 sexplib.113.00.00 cow.1.4.0 unix-errno.0.2.0 unix-fcntl.0.2.0</code></pre>

I had this github repo pinned in opam.

As a user you probably want to `opam pin add <pkg> <version>` all of those, to not run into problems with `opam upgrade` or later package installations,

Reasons:
- sha.1.9 [fails to patch 'freebsd.patch'](https://github.com/ocaml/opam-repository/issues/6343).
- sexplib >= 113.24.00 has changes that have to do with "ppx", and isn't found by sibylfs.
- cow 2.0.0, cow.syntax is not found by sibylfs compilation.
- unix-errno and unix-fcntl >= 0.3.0 are not found by the compilation step of sibylfs (also "ppx" related?).

The last three items can probably be fixed on your end.

**Comment by tomjridge** [comment]
Thanks for the bug report.

Yes, this is the problem with opam approaches. Hopefully the nix install works fine?

@dsheets  can you make the fixes?

**Comment by HenkPoley** [comment]
I might look further into it (e.g. Nix) once these syscalls are implemented in 'Windows Subsystem for Linux':
- [mount](https://github.com/Microsoft/BashOnWindows/issues/131), though missing loopback device can be worked around with `--model path=<some actual path>`
- [chroot](https://github.com/Microsoft/BashOnWindows/issues/47), I didn't look into it if you can convince SibylFS to drop the `chroot` requirement. Probably by commenting out [this line](https://github.com/sibylfs/sibylfs_src/blob/ec6d449d98fd3d1419c17ccfdc88472c45c8a844/fs_test/lib/posix_agent.ml#L88). But it will then try to manipulate `/` :-(

Would be neat to check their POSIX filesystem conformance :P

**Comment by tomjridge** [comment]
Ah! You are running on windows via some kind of ubuntu compatibility layer on top of windows?

Yes, mount you can probably work around. And also chroot. But for obvious reasons be careful if you omit  chroot!

**Comment by dsheets** [comment]
I've fixed the pinning `opam` file in this repository in #15 and I have put the upper bound on `unix-fcntl` in ocaml/opam-repository#6346. As I said in ocaml/opam-repository#6343, the `sha.1.9` issue is likely a file system bug in WSL.

It would indeed be neat to check WSL's POSIX conformance but I'm afraid it's probably too incomplete and unstable at this time. I appreciate your trying to get this to work and your report regarding missing dependency constraints. Please, let us know if you encounter other issues.

**Comment by HenkPoley** [comment]
Be sure to note that you are not supposed to make any changes for WSL if something works on Linux. Microsoft ought to take care of missing functionality. Though maybe the case of missing chroot() could be looked into. Possibly a "soft-chroot" where all the traces proveably don't go outside a certain path could be neat for running SibylFS on even dumber OSes.

**Comment by tomjridge** [comment]
If you do get it to work, it would be very interesting to see the results! We can post them on the sibylfs.io website also.

**Comment by HenkPoley** [comment]
`proot` might be an interesting alternative to chroot and mounting. Though then you will be working through QEMU user-mode. Which could be interesting to test in it's own regard anyways.
